"""initial migration

Revision ID: c4be9c82a6b9
Revises: 
Create Date: 2026-06-24 14:24:06.371094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision: str = 'c4be9c82a6b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('informations_generales',
    sa.Column('idEvaluation', UUID(as_uuid=True), nullable=False),
    sa.Column('dateEvaluation', sa.Date(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('prenom', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('mobile', sa.String(), nullable=True),
    sa.Column('entreprise', sa.String(), nullable=True),
    sa.Column('secteurActivite', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('idEvaluation')
    )
    op.create_table('cicd',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('utiliseCICD', sa.Boolean(), nullable=True),
    sa.Column('outil', sa.String(), nullable=True),
    sa.Column('testPerformanceIntegre', sa.Boolean(), nullable=True),
    sa.Column('momentTest', sa.String(), nullable=True),
    sa.Column('informations_id', UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['informations_id'], ['informations_generales.idEvaluation'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gestion_projet',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('typeMethode', sa.String(), nullable=True),
    sa.Column('informations_id', UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['informations_id'], ['informations_generales.idEvaluation'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('impact',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('nombreRessources', sa.Integer(), nullable=True),
    sa.Column('coutIncident', sa.Float(), nullable=True),
    sa.Column('tempsResolution', sa.String(), nullable=True),
    sa.Column('causesRework', sa.String(), nullable=True),
    sa.Column('problemeRessources', sa.String(), nullable=True),
    sa.Column('informations_id', UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['informations_id'], ['informations_generales.idEvaluation'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performance',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('degradationPerformance', sa.String(), nullable=True),
    sa.Column('impactVentes', sa.Boolean(), nullable=True),
    sa.Column('testsChargeRealises', sa.String(), nullable=True),
    sa.Column('typeTestCharge', sa.String(), nullable=True),
    sa.Column('informations_id', UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['informations_id'], ['informations_generales.idEvaluation'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tests_fonctionnels',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('anomaliesProduction', sa.String(), nullable=True),
    sa.Column('testsFonctionnelsRealises', sa.String(), nullable=True),
    sa.Column('typeTest', sa.String(), nullable=True),
    sa.Column('informations_id', UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['informations_id'], ['informations_generales.idEvaluation'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integration_outils',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('typeIntegration', sa.String(), nullable=False),
    sa.Column('gestion_projet_id', UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['gestion_projet_id'], ['gestion_projet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outil_gestion_projet',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('gestion_projet_id', UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['gestion_projet_id'], ['gestion_projet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outil_test_fonctionnel',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('tests_fonctionnels_id', UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['tests_fonctionnels_id'], ['tests_fonctionnels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outil_test_performance',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('performance_id', UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['performance_id'], ['performance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outil_test_performance')
    op.drop_table('outil_test_fonctionnel')
    op.drop_table('outil_gestion_projet')
    op.drop_table('integration_outils')
    op.drop_table('tests_fonctionnels')
    op.drop_table('performance')
    op.drop_table('impact')
    op.drop_table('gestion_projet')
    op.drop_table('cicd')
    op.drop_table('informations_generales')
    # ### end Alembic commands ###
