"""add distribution charge column to cicd

Revision ID: d3e29878871a
Revises: c4be9c82a6b9
Create Date: 2026-06-26 10:10:56.792359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3e29878871a'
down_revision: Union[str, None] = 'c4be9c82a6b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cicd', sa.Column('distributionCharge', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cicd', 'distributionCharge')
    # ### end Alembic commands ###
